sipa/bips

bip-schnorr.mediawiki

In signature signing formula, the secret key "d" was misspelled as "x". Fixed.

Fix typo in signature signing formula.

---

bip-schnorr.mediawiki

Replacing the link destination to one managed by Springer Verlag (copyright owner).
See page 132 in the old reference for an example of cropping.

Link to Pedersen sharing with uncropped pages

---

bip-schnorr.mediawiki

* public key not defined in signing section (Russel)
* wrong private key in signing section (Artem & Russel)
* Jacobian coordinates section doesn't take point at infinity into account (Russel)
* reference code misses some modular reductions (Artem)

Fix issues in the Schnorr BIP discovered by Russel O'Connor and Artem Litvinovich

---

bip-schnorr.mediawiki

* add reference to BIP66 in addition to BIP62
* state who picks ''e'' and ''s'' and does the revealing (less use of passive voice FTW)
* explicitly state  option 3 was chosen
* remind reader where all the weird constants come from the sekp256k1 standard
* add missing subscript i

Minor readability improvements, typo fix

---

bip-schnorr.mediawiki

A PRG alone is not sufficient. We need a hash function, and then I think this can be proven secure in the ROM (it forces the attacker to choose the other inputs first, in a Fiat-Shamir style).
One thing to keep in mind:
If batch verification is deterministic, one problem is that different implementations could use different ways to generate the random numbers, and arrive at different results. The probability that this happens is negligible however (unless the hash function is terribly broken).

Use a hash to seed the CSPRNG for batch verification

---

bip-schnorr.mediawiki

This should not change the behavior.
* 1-to-1 correspondence to functions in pseudocode
* naming of functions closer to pseudocode
* lowercase / uppercase names more consistent (also avoids shadowing of p)
* more consistent parentheses
* don't reassign to k in signing algorithm (#7)
I didn't want to go further and really have identical function names. The pseudocode makes use of overloading, and also `int` and `hash` and built-in functions in python.

Improve readability of Python implementation

---

bip-schnorr.mediawiki

As per @real-or-random's suggestion:
1. Specifically state the inputs of seed derivation
2. Remove note that these numbers can be generated "randomly" because it seems much more robust to use a CSPRNG seeded by the inputs instead of system randomness (which can be predictable in VMs, or low entropy)...
3. Mention libsecp implementation as an example (and specifically mention chacha20)

Clarify random number generation in batch verification

---

bip-taproot.mediawiki

If we look at
```
def IsPayToTaproot(script):
return len(script) == 35 and script[0] == OP_1 and script[1] == 33 and script[2] >= 0 and script[2] <= 1
```
(from test_framework/script.py)
First byte is is checked for OP_1. OP_1 is 0x51
But the example code in `taproot_output_script` returns  
`bytes([0x01, 0x21, output_pubkey[0] & 1]) + output_pubkey[1:]`
First byte 0x01, but it should be 0x51

taproot_output_script: first returned byte should be OP_1 (0x51)

---

bip-schnorr.mediawiki

[pedantic nit] 'Quadratic residue of y' does not exist. Reword this as 'Whether y is a quadratic residue'.

Reword 'quadratic residue of...'

---

bip-taproot.mediawiki

`sign_internal_key` is a always a bit confusing because you actually sign for the output key (but you're using the internal privkey).

Use key path spend terminology more consistently in taproot/tapscript

---

bip-taproot.mediawiki

Also moved `taproot_tree_helper` to the top of the function because that seemed more logical.

Fix privkey negation in taproot_sign_key

---

bip-taproot.mediawiki

Afaik @apoelstra came up with this attack. Mitigating this by adding an unspendable script path was suggested by @real-or-random.

Prescribe that an output key should always have a taproot commitment

---

bip-schnorr.mediawiki

threshold sigs:
- explain limitations of the state of the art, cite more schemes
blind sigs:
- remove Schnorr's mitigation because this results in incompatible signatures
- cite new paper by Fuchsbacher, Plouviez and Seurin 
general:
- tone down the enthusiasm a little bit
- minor improvements
- be conservative and remove speculations

Rework Applications section

---

bip-tapscript.mediawiki

This seems no longer necessary with the introduction of 32B public keys.

Removed reference to 0xc1 leaf version.

---

bip-schnorr.mediawiki

A small nit about the Euler's Criterion working only on prime modulo (Legendre's symbol as opposed to Jacobi Symbol)
Not sure if it's really needed but nice to be explicit (maybe also a comment on the python code? https://github.com/sipa/bips/blob/bip-schnorr/bip-schnorr/reference.py#L56)

Euler's Criterion prime only nit

---

bip-taproot.mediawiki

definition of spend_type calls it bit 0, but sha_annex definition references bit 1

annex is bit 0 of spend_type

---

bip-taproot.mediawiki

Currently github markdown renders `b''` inside `<source>` tags incorrectly. This makes `h = b''` show as `h = b` and creates some confusion.
The issue can be avoided by using bytes() to create empty byte array.
Fixing this way may be beneficial even if github markdown is fixed, because this prevents similar issue with other rendering engines.

bip-taproot: use bytes() instead of b'' - avoid markdown issue

---

bip-taproot.mediawiki

the final "-None" line in the docstring of `taproot_output_script` example function was actually outside of the docstring

bip-taproot: fix docstring in taproot_output_script

---

bip-taproot.mediawiki

For the key spend the script tree depth is not revealed, it is only done for script spends. This sentence makes sense only for the script spend.

fix: script spend, not key spend reveals tree depth

---

bip-taproot.mediawiki

Fixes #127 
As suggested by @sipa

Internal pubkey calculation fixed in taproot_tweak_pubkey()

---

bip-taproot.mediawiki
bip-tapscript.mediawiki

Per https://github.com/bitcoin/bips/blob/master/bip-0001.mediawiki:
"BIPs may have a Requires header, indicating the BIP numbers that this BIP depends on"
Given the scope of the Taproot/Schnorr improvements I think it's important to include all mandatory dependencies of Taproot in the BIP's header.
Currently a placeholder to be replaced with actual BIP number if this BIP/Schnorr proceeds further.

ADD: Require BIPs for Taproot and Tapscript

---

bip-taproot.mediawiki

as per the discussion from http://www.erisian.com.au/taproot-bip-review/log-2019-11-12.html#l-120:
- update the paragraph in question to more clearly convey that the helper
functions, and not the Python3 example code, are from the bip-schnorr
reference code
- add a link to the reference code in
https://github.com/sipa/bips/blob/bip-schnorr/bip-schnorr/reference.py

 bip-taproot: clarify bip-schnorr reference code

---

bip-schnorr.mediawiki

Throughout the document, multiplication is denoted with dots, as in `d'⋅G` as opposed to `d'G`.
This is not the case in two places in the 'Default Signing' section.
Missing dots are added for consistency.

Nit: bip-schnorr: Add missing dots that denote multiplication

---

bip-taproot.mediawiki

Another attempt at simplifying terminology. `has_square_y` is good for bip-schnorr and what happens at the low level. But I think for the taproot signing functions it's better to call it `is_negated`. This came up in particular when writing the libsecp API. `has_square_y` as a return value of taproot_tweak is really difficult to explain because what exactly has a square y? An unnamed point that was the outcome of the taproot tweak but that's not there anymore. `is_negated` on the other hand just indicates whether the return public key was negated or not, and also makes it a bit more clear that you need the bit again for taproot verifying.
This PR also fixes an issue where the wrong `output_pubkey_tag` is computed.

Rename is_y_square to is_negated in taproot signing

---

bip-schnorr.mediawiki

Right now both secret and private key are used to describe the same thing. Better to just standardize on one. I'm suggesting to use terminology matching libsecp.

Replace private key with secret key

---

bip-taproot.mediawiki

Writing this out was helpful for me to understand the order in which branch hashes are serialized in the control block. It may be clear in the python snippets, but the thing that was missing for me was this exact visual sequence:
```
To spend from script D, control block contains these hashes in order: C, E, AB
```
I was confused because I assumed the hashes in the control block were more like SPV merkle-tree proofs, which would imply an order of `AB, C, E` -- but then that wouldn't make sense because the algorithm _starts_ with the TapLeaf hash of D.

bip-taproot: Explain example from script-tree diagram

---

bip-schnorr.mediawiki

- Separate nonce generation into getting a random byte string and converting it to a suitable scalar ...
- ... to make clear that the byte string can be generated differently. 
- Make the warning a little bit more prominent and improve writing

clarify nonce generation

---

bip-taproot.mediawiki
bip-tapscript.mediawiki

Instead of having seemingly-arbitrary numbers (0xc0) for leaf versions, redefine leaf version to just be the 5 relevant middle bits of the control block first byte. Use xor rather than masking to not theoretically rule out the ability to use leaf versions which don't set the top 2 bits.
EDIT: after significant revisions by @ajtowns, it no longer actually changes the leaf version definition, instead just improving the rationale.

Rewrite leaf versions rationale

---

bip-0340.mediawiki

* Recommend a byte length for aux random data
* Clarify that with signature verification by default at the end of the signing algorithm, using public keys from untrusted sources is not an issue.  
*  A few editorial nits

Fix a few minor issues

---

bip-0340.mediawiki
bip-0340/reference.py
bip-0340/test-vectors.py

solves https://github.com/sipa/bips/issues/188
Tell me if I overdid it. But I think it's still readable, in particular if you have syntax highlighting and the comments are displayed differently.
This also adjusts the variables to match the BIP text. 
I should have based this on top of #196, sorry. Let's first get #196 merged and I can rebase.

Add debug print for intermediate values 

---

bip-0341.mediawiki

`is_negated` is a relic from when squareness was used as a tie breaker. This makes it more obvious what happens during verification and shows that the result of taproot_tweak is essentially compressed pubkey serialization. Also, it looks like we mixed up 0 and 1 with `is_negated`, so I changed that as well.

BIP-0341: Replace notion of is_negated with parity bit

---

bip-0340/reference.py

<s>This is on top of #200.</s>
Typing makes the code easier to read. It also makes it easier to see where assumptions about non-infinity are being made.

Typing annotations for BIP-0340

---

bip-0340.mediawiki
bip-0340/reference.py
bip-0340/test-vectors.py

Also make sure `has_even_y` is well-defined for infinity input.
Pointed out in https://github.com/bitcoin-core/secp256k1/pull/558#discussion_r481658725

Clarify that R=infinity is invalid in BIP340
